name: task_list_app
description: Task list application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  hooks_riverpod: ^2.1.3
  flutter:
    sdk: flutter
  go_router: ^8.0.3

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
